### ISSUE TITLE
[Model Issue] Importing APP_PD model

### ISSUE THREAD

**Issue by jongwon-han** [LolitaZJ/Atten_Polarity_Model#1]
Hi, this is Jongwon Han, currently a PhD student at Korea University.

I would like to apply and test your polarity model in my research related to polarity determination, but there is an issue with the model provided on GitHub.

There is no problem loading the Ross models in the model directory, but all the pd models have issues.

It seems that the problem might have occurred in the model file due to the addition of the SeqSelfAttention layer.
I am also sending you a capture of the traceback I am experiencing.

Please check it when you have time.

![image](https://github.com/LolitaZJ/Atten_Polarity_Model/assets/91581397/0f785b1d-2a71-4dce-b30b-ba1eb7adbb48)

**Comment by LolitaZJ** [comment]
Hi Jongwon, Thank you for posting the issue.

Regarding your question, it seems that the TensorFlow version or the usage of the 'load_model' function within the 'keras.models' module. I noticed that you used 'load_model' function from 'tf.keras.models'.

In my environment, which consists of Python 3.8.8, Keras 2.7.0,Kears-self-attention 0.50.0 and TensorFlow-GPU 2.7.0, I have encountered no problems with the 'load_model' function of the pd models.

Hope this information proves helpful to you.

Best regards,
Ji

**Comment by jongwon-han** [comment]
Thanks, Ji! 

Based on the versions you provided, I was able to set up the virtual environment, and it works well now.
There is also no problem with the prediction process. 

Thank you again, it has been very helpful for my research.

Cheers,
Jongwon
